export { Velobase } from "./client";
export {
  VelobaseError,
  VelobaseAuthenticationError,
  VelobaseValidationError,
  VelobaseNotFoundError,
  VelobaseConflictError,
  VelobaseInternalError,
} from "./errors";
export type {
  VelobaseOptions,
  BusinessType,
  FreezeParams,
  FreezeResponse,
  ConsumeParams,
  ConsumeResponse,
  UnfreezeParams,
  UnfreezeResponse,
  DeductParams,
  DeductResponse,
  DepositParams,
  DepositResponse,
  WalletSource,
  WalletBalance,
  CustomerResponse,
  LedgerParams,
  LedgerEntry,
  LedgerResponse,
  SlotEventType,
  SlotPoolStatus,
  SlotPoolView,
  SlotPoolSummary,
  GrantCapacityParams,
  GrantCapacityResponse,
  RevokeCapacityParams,
  RevokeCapacityResponse,
  ClaimSlotParams,
  ClaimSlotResponse,
  ReleaseSlotParams,
  ReleaseSlotResponse,
  GetCustomerSlotsResponse,
  ListSlotEventsParams,
  ListSlotEventsResponse,
  SlotEventEntry,
  EntitlementEventType,
  EntitlementView,
  SetEntitlementParams,
  SetEntitlementResponse,
  GetEntitlementParams,
  GetEntitlementResponse,
  ListEntitlementsParams,
  ListEntitlementsItem,
  ListEntitlementsResponse,
  RemoveEntitlementParams,
  RemoveEntitlementResponse,
  ListEntitlementEventsParams,
  ListEntitlementEventsResponse,
  EntitlementEventEntry,
} from "./types";

// default export for convenience
export { Velobase as default } from "./client";
